# Generated by Django 4.2.7 on 2023-11-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='best',
            field=models.BooleanField(default=False, verbose_name='جزو بهترین مقالات'),
        ),
    ]
