# Generated by Django 4.2.7 on 2024-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_emails_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=400, unique=True, verbose_name='ایمیل'),
        ),
    ]
